### ISSUE TITLE
Crash on boot when installed on Server

### ISSUE THREAD

**Issue by Dumpling00** [ViciousBadger/larion-world-generation#1]
Hey there, would really love to use this on a server but whenever I try to add it in and run it, it shuts itself down after a couple of seconds without even generating an error code - is it possible  to make it work?
(Fabric 1.20.1)

Thanks for your time and consideration.

**Comment by ViciousBadger** [comment]
Hi, thanks for reaching out. Can you paste the output log from the server? Otherwise there's not much i can do to help unfortunately

**Comment by Dumpling00** [comment]
So I managed to snap a video of it, and isolating the last frame or so gives us this error:
https://github.com/ViciousBadger/larion-world-generation/assets/44829013/febbf491-bcff-4b2e-b37c-ce58b014691d

![image](https://github.com/ViciousBadger/larion-world-generation/assets/44829013/01511eba-c6ed-4aa5-b42f-78d3f141df1b)
Not sure if this helps?

**Comment by Dumpling00** [comment]
Okay yeah ignore me, I'm an idiot, I thought More Density was only to be installed on the client side.
Sorry to waste your time!

**Comment by ViciousBadger** [comment]
Actually it's only required on the server side! And no worries, no time wasted :)
