### ISSUE TITLE
1.20?

### ISSUE THREAD

**Issue by RexkUr** [ViciousBadger/larion-world-generation#4]
just requesting for a backport of Larion for 1.20. its a really cool mod that i enjoy and would like it to be backported and supported possibly? (no pressure though)

**Comment by ViciousBadger** [comment]
I will look into it soon, supporting multiple versions with mods is new to me and Gradle is confusing. Which version exactly? 1.20.1? 1.20.4..?

**Comment by RexkUr** [comment]
1.20.1 would be ideal

**Comment by ViciousBadger** [comment]
v3.6 has just been released w/ backports to 1.20-1.20.6, solving this issue :)
